Algoritmo "SelecaoMultiplaEscolha"

Var
   codigo : Inteiro
Inicio
   codigo <- 2 //Código escolhido.

    Escolha (código)
        Caso 1
           Escreval ("O produto é um perfume.")
        Caso 2
           Escreval ("O produto é um shampoo.") //Vai imprimir essa linha.
        Caso 3
           Escreval ("O produto é um pente.")
        Caso 4
           Escreval ("O produto é um sabonete.")
    FimEscolha
Fimalgoritmo